# Generated by Django 5.1.1 on 2024-10-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='orderid',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='productname',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='producttype',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notitype',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderid',
            field=models.CharField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='productname',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='producttype',
            field=models.CharField(blank=True, null=True),
        ),
    ]
