# Generated by Django 5.1.1 on 2024-11-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_notification_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeproducts',
            name='descr',
            field=models.CharField(blank=True, max_length=625),
        ),
        migrations.AddField(
            model_name='coffeproducts',
            name='ratingnumber',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
