# Generated by Django 5.1.1 on 2024-11-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_coffeproducts_descr_coffeproducts_ratingnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeproducts',
            name='descr',
            field=models.CharField(blank=True),
        ),
    ]
