# Generated by Django 5.1.1 on 2024-11-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_alter_coffeproducts_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeproducts',
            name='ratingnumber',
            field=models.CharField(blank=True, null=True),
        ),
    ]
